<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>OptiTherm Project: Digital Twin and Energy-Efficient Predictive Control (Data-Driven MPC) – Ismaël Tchinda Ngueyong | Portfolio</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-6f4c31e05982fe9d7c1d5110dfef5365.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-1dd26af7942a9f2a0e9e560fe99add0c.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-6f4c31e05982fe9d7c1d5110dfef5365.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-9437f62aa451a97c7672acc9cb6e03fe.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-68603670fbd6a1c0ab91dcecad0eda46.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../site_libs/bootstrap/bootstrap-9437f62aa451a97c7672acc9cb6e03fe.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<meta name="google-site-verification" content="_nP-5a2L5SUdkPSgoUt78tiCYEIVJVAX2enqgA2qouA">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-sidebar floating nav-fixed quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Ismaël Tchinda Ngueyong | Portfolio</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../ai-ml/index.html"> 
<span class="menu-text">Deep Learning &amp; AI</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../scientific-computing/index.html"> 
<span class="menu-text">Scientific Computing</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html"> 
<span class="menu-text">About Me</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../cv.html"> 
<span class="menu-text">Resume</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../ai-ml/optitherm.html">OptiTherm (Digital Twin)</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../ai-ml/ml-engine.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">ML Engine (NumPy)</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../ai-ml/blobs_classification.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Multiclass Classification with ml-engine-from-scratch</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../ai-ml/moons_classification.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Binary Classification of Non-Linear Data (Moons)</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../ai-ml/multi_output_regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Multi-Output Non-Linear Regression</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../ai-ml/optitherm.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">OptiTherm (Digital Twin)</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#business-context-and-objective" id="toc-business-context-and-objective" class="nav-link active" data-scroll-target="#business-context-and-objective">1. Business Context and Objective</a></li>
  <li><a href="#the-dataset-reproducibility" id="toc-the-dataset-reproducibility" class="nav-link" data-scroll-target="#the-dataset-reproducibility">2. The Dataset &amp; Reproducibility</a></li>
  <li><a href="#case-study-the-panther_office_graham-building" id="toc-case-study-the-panther_office_graham-building" class="nav-link" data-scroll-target="#case-study-the-panther_office_graham-building">3. Case Study: The <em>Panther_office_Graham</em> Building</a></li>
  <li><a href="#methodology-and-roadmap" id="toc-methodology-and-roadmap" class="nav-link" data-scroll-target="#methodology-and-roadmap">4. Methodology and Roadmap</a></li>
  <li><a href="#stage-1-data-engineering-and-consolidation-1" id="toc-stage-1-data-engineering-and-consolidation-1" class="nav-link" data-scroll-target="#stage-1-data-engineering-and-consolidation-1">Stage 1: Data Engineering and Consolidation</a></li>
  <li><a href="#stage-2-exploratory-data-analysis-eda-and-missing-data-handling" id="toc-stage-2-exploratory-data-analysis-eda-and-missing-data-handling" class="nav-link" data-scroll-target="#stage-2-exploratory-data-analysis-eda-and-missing-data-handling">Stage 2: Exploratory Data Analysis (EDA) and Missing Data Handling</a>
  <ul class="collapse">
  <li><a href="#data-quality-assessment-and-cleaning-strategy" id="toc-data-quality-assessment-and-cleaning-strategy" class="nav-link" data-scroll-target="#data-quality-assessment-and-cleaning-strategy">Data Quality Assessment and Cleaning Strategy</a></li>
  <li><a href="#sequential-data-preparation-and-tensor-construction" id="toc-sequential-data-preparation-and-tensor-construction" class="nav-link" data-scroll-target="#sequential-data-preparation-and-tensor-construction">Sequential Data Preparation and Tensor Construction</a></li>
  </ul></li>
  <li><a href="#stage-4-thermallstm-architecture-definition" id="toc-stage-4-thermallstm-architecture-definition" class="nav-link" data-scroll-target="#stage-4-thermallstm-architecture-definition">Stage 4: ThermalLSTM Architecture Definition</a></li>
  <li><a href="#stage-5-thermallstm-training-and-model-optimization" id="toc-stage-5-thermallstm-training-and-model-optimization" class="nav-link" data-scroll-target="#stage-5-thermallstm-training-and-model-optimization">Stage 5: ThermalLSTM Training and Model Optimization</a>
  <ul class="collapse">
  <li><a href="#conclusion-and-engineering-insights" id="toc-conclusion-and-engineering-insights" class="nav-link" data-scroll-target="#conclusion-and-engineering-insights">5. Conclusion and Engineering Insights</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">OptiTherm Project: Digital Twin and Energy-Efficient Predictive Control (Data-Driven MPC)</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="business-context-and-objective" class="level3">
<h3 class="anchored" data-anchor-id="business-context-and-objective">1. Business Context and Objective</h3>
<p>Improving the energy efficiency of commercial buildings is both a financial and environmental priority. Conventional Heating, Ventilation, and Air Conditioning (HVAC) systems typically rely on reactive, rule-based control strategies (e.g., fixed thermostat setpoints), without accounting for the building’s complex thermal dynamics or weather forecasts.</p>
<p><strong>The objective of this project</strong> is to develop a <strong>data-driven Model Predictive Control (MPC)</strong> framework. The proposed approach consists of:</p>
<ol type="1">
<li>Learning the building’s thermal and energy dynamics using a deep neural network that serves as a <strong>digital twin</strong>.</li>
<li>Integrating this predictive model with an optimization algorithm to compute the optimal control strategy that minimizes energy consumption while maintaining occupants’ thermal comfort.</li>
</ol>
</section>
<section id="the-dataset-reproducibility" class="level3">
<h3 class="anchored" data-anchor-id="the-dataset-reproducibility">2. The Dataset &amp; Reproducibility</h3>
<p>To ground this project in a real-world application, we use the <strong>Building Data Genome 2 (BDG2)</strong> dataset.</p>
<blockquote class="blockquote">
<p><strong>To run this notebook locally:</strong> You can download the data directly via the Kaggle API. Ensure your Kaggle API credentials are set up on your machine, then run the setup cell below to fetch and extract the data into the <code>archive/</code> directory.</p>
</blockquote>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>How to set up Kaggle API credentials
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li>Log in to your <a href="https://www.kaggle.com/">Kaggle</a> account and navigate to <strong>Settings</strong>.</li>
<li>Scroll down to the <strong>API</strong> section and generate a new token. Kaggle will provide you with a <strong>Username</strong> and a <strong>Key</strong>.</li>
<li>You can authenticate in one of two ways:</li>
</ol>
<p><strong>Option A: Directly in Python (Easiest)</strong> Add a new cell at the top of your notebook with your credentials:</p>
<pre><code>import os
os.environ['KAGGLE_USERNAME'] = "your_username"
os.environ['KAGGLE_KEY'] = "your_api_key"</code></pre>
<p><em>Important: If you use this method, remember to delete your key from the cell before pushing the notebook to GitHub!</em></p>
<p><strong>Option B: System Environment Variables (Most Secure)</strong></p>
<ul>
<li><strong>Windows (Command Prompt):</strong> <code>setx KAGGLE_USERNAME "your_username"</code> and <code>setx KAGGLE_KEY "your_api_key"</code></li>
<li><strong>Mac/Linux (Terminal):</strong> Add <code>export KAGGLE_USERNAME="your_username"</code> and <code>export KAGGLE_KEY="your_api_key"</code> to your <code>~/.bashrc</code> or <code>~/.zshrc</code> file.</li>
</ul>
</div>
</div>
</div>
<hr>
<div id="02d73832" class="cell" data-execution_count="1">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> os</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Install the kaggle package (uncomment the lines below if running for the first time)</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="co"># %pip install -q kaggle</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="co"># os.environ['KAGGLE_USERNAME'] = "your_kaggle_user_name"</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="co"># os.environ['KAGGLE_KEY'] = "your_kaggle_api_token"</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Download and unzip the dataset directly into the archive folder</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>os.makedirs(<span class="st">"archive"</span>, exist_ok<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Downloading BDG2 dataset from Kaggle..."</span>)</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a><span class="op">!</span>kaggle datasets download <span class="op">-</span>d claytonmiller<span class="op">/</span>buildingdatagenomeproject2 <span class="op">-</span>p archive<span class="op">/</span> <span class="op">--</span>unzip</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Download and extraction complete!</span><span class="ch">\n</span><span class="st">"</span>)</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the building metadata</span></span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>df_meta <span class="op">=</span> pd.read_csv(<span class="st">"archive/metadata.csv"</span>)</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"--- Building Categories ---"</span>)</span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(df_meta[<span class="st">"primaryspaceusage"</span>].value_counts().head(<span class="dv">10</span>))</span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter office buildings</span></span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a>offices <span class="op">=</span> df_meta[df_meta[<span class="st">"primaryspaceusage"</span>] <span class="op">==</span> <span class="st">"Office"</span>]</span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">--- Sample Office Buildings ---"</span>)</span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(offices[[<span class="st">"building_id"</span>, <span class="st">"site_id_kaggle"</span>, <span class="st">"sqm"</span>, <span class="st">"yearbuilt"</span>]].head())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Downloading BDG2 dataset from Kaggle...
Download and extraction complete!

--- Building Categories ---
primaryspaceusage
Education                        617
Office                           307
Entertainment/public assembly    204
Lodging/residential              168
Public services                  166
Other                             29
Healthcare                        29
Parking                           24
Warehouse/storage                 15
Manufacturing/industrial          13
Name: count, dtype: int64

--- Sample Office Buildings ---
               building_id  site_id_kaggle     sqm  yearbuilt
5     Panther_office_Daina             0.0   133.8     1983.0
7   Panther_office_Woodrow             0.0   537.8     1996.0
16    Panther_office_Karla             0.0  2508.4     2010.0
23   Panther_office_Graham             0.0  7799.9     1974.0
25  Panther_office_Valarie             0.0  1416.8     1980.0</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>'kaggle' is not recognized as an internal or external command,
operable program or batch file.</code></pre>
</div>
</div>
</section>
<section id="case-study-the-panther_office_graham-building" class="level3">
<h3 class="anchored" data-anchor-id="case-study-the-panther_office_graham-building">3. Case Study: The <em>Panther_office_Graham</em> Building</h3>
<p>After exploring the metadata above, we identified an ideal candidate for developing our digital twin:</p>
<ul>
<li><strong>Building ID:</strong> <code>Panther_office_Graham</code> (<em>Kaggle Site ID: 0.0</em>)</li>
<li><strong>Building type:</strong> Office</li>
<li><strong>Floor area:</strong> <span class="math inline">\(7,800\, m^2\)</span></li>
<li><strong>Year of construction:</strong> 1974</li>
</ul>
<section id="why-this-building" class="level4">
<h4 class="anchored" data-anchor-id="why-this-building">Why this building?</h4>
<p>Office buildings exhibit well-defined daily and weekly occupancy patterns, with low occupancy during nights and weekends. In addition, a building constructed in 1974 is likely to have significant thermal inertia and relatively poor insulation compared with modern standards. These characteristics make it an ideal candidate for a predictive AI-based control system, as substantial energy savings can be achieved by anticipating heating and cooling demands while maintaining occupant comfort.</p>
</section>
</section>
<section id="methodology-and-roadmap" class="level3">
<h3 class="anchored" data-anchor-id="methodology-and-roadmap">4. Methodology and Roadmap</h3>
<p>The project is organized into four iterative stages. At each stage, architectural and modeling decisions are driven by insights gained from the data.</p>
<section id="stage-1-data-engineering-and-consolidation" class="level4">
<h4 class="anchored" data-anchor-id="stage-1-data-engineering-and-consolidation"><strong>Stage 1: Data Engineering and Consolidation</strong></h4>
<p><strong>Challenge:</strong> The raw data are distributed across large files containing utility meter readings (electricity, chilled water, steam, etc.) and weather station measurements, totaling several gigabytes.</p>
<p><strong>Objective:</strong> Extract the time series corresponding to the target building and merge them with the associated local weather data to create a clean, lightweight, and analysis-ready dataset.</p>
<hr>
</section>
<section id="stage-2-exploratory-data-analysis-eda-and-preprocessing" class="level4">
<h4 class="anchored" data-anchor-id="stage-2-exploratory-data-analysis-eda-and-preprocessing"><strong>Stage 2: Exploratory Data Analysis (EDA) and Preprocessing</strong></h4>
<p><strong>Challenge:</strong> Real-world time series are noisy, contain missing values, and exhibit strong seasonal and cyclical patterns.</p>
<p><strong>Objective:</strong> Explore the relationships between weather variables and energy consumption, handle missing values using appropriate interpolation techniques, and encode temporal cyclicality (e.g., sine/cosine transformations of hour and day) to prepare the data for deep learning models.</p>
<hr>
</section>
<section id="stage-3-learning-the-building-dynamics-deep-learning-with-pytorch" class="level4">
<h4 class="anchored" data-anchor-id="stage-3-learning-the-building-dynamics-deep-learning-with-pytorch"><strong>Stage 3: Learning the Building Dynamics (Deep Learning with PyTorch)</strong></h4>
<p><strong>Challenge:</strong> A building’s thermal state at time <em>t</em> depends on its previous states due to thermal inertia. Consequently, conventional regression models are unable to capture these long-term temporal dependencies.</p>
<p><strong>Objective:</strong> Train a recurrent neural network (LSTM or GRU) on sliding time windows to predict future energy consumption and/or thermal states from weather conditions and control variables.</p>
<hr>
</section>
<section id="stage-4-control-strategy-optimization-model-predictive-control" class="level4">
<h4 class="anchored" data-anchor-id="stage-4-control-strategy-optimization-model-predictive-control"><strong>Stage 4: Control Strategy Optimization (Model Predictive Control)</strong></h4>
<p><strong>Challenge:</strong> Accurate forecasting alone is not sufficient; the ultimate goal is to minimize energy costs while preserving occupant comfort.</p>
<p><strong>Objective:</strong> Freeze the neural network parameters and use a numerical optimization algorithm (e.g., L-BFGS-B from SciPy) to compute the optimal control sequence that minimizes a cost function combining energy consumption and thermal discomfort penalties.</p>
</section>
</section>
<section id="stage-1-data-engineering-and-consolidation-1" class="level2">
<h2 class="anchored" data-anchor-id="stage-1-data-engineering-and-consolidation-1">Stage 1: Data Engineering and Consolidation</h2>
<div id="76828ed4" class="cell" data-execution_count="2">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Parameters for the digital twin</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>building_id <span class="op">=</span> <span class="st">"Panther_office_Graham"</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>site_id <span class="op">=</span> <span class="st">"Panther"</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"1. Extracting electricity consumption data..."</span>)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>df_elec <span class="op">=</span> pd.read_csv(<span class="st">"archive/electricity_cleaned.csv"</span>, usecols<span class="op">=</span>[<span class="st">"timestamp"</span>, building_id])</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>df_elec.rename(columns<span class="op">=</span>{building_id: <span class="st">"meter_reading"</span>}, inplace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>df_elec[<span class="st">"timestamp"</span>] <span class="op">=</span> pd.to_datetime(df_elec[<span class="st">"timestamp"</span>])</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"2. Extracting weather data (Site: </span><span class="sc">{</span>site_id<span class="sc">}</span><span class="ss">)..."</span>)</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>df_weather <span class="op">=</span> pd.read_csv(<span class="st">"archive/weather.csv"</span>)</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>df_weather_site <span class="op">=</span> df_weather[df_weather[<span class="st">"site_id"</span>] <span class="op">==</span> site_id].copy()</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>df_weather_site.drop(columns<span class="op">=</span>[<span class="st">"site_id"</span>], inplace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>df_weather_site[<span class="st">"timestamp"</span>] <span class="op">=</span> pd.to_datetime(df_weather_site[<span class="st">"timestamp"</span>])</span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"3. Merging time series..."</span>)</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>df_merged <span class="op">=</span> pd.merge(df_elec, df_weather_site, on<span class="op">=</span><span class="st">"timestamp"</span>, how<span class="op">=</span><span class="st">"inner"</span>)</span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>df_merged.set_index(<span class="st">"timestamp"</span>, inplace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a>df_merged.sort_index(inplace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">Dataset shape: </span><span class="sc">{</span>df_merged<span class="sc">.</span>shape[<span class="dv">0</span>]<span class="sc">}</span><span class="ss"> hourly observations $</span><span class="ch">\\</span><span class="ss">times$ </span><span class="sc">{</span>df_merged<span class="sc">.</span>shape[<span class="dv">1</span>]<span class="sc">}</span><span class="ss"> features"</span>)</span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">--- Data Quality Report (Missing Values) ---"</span>)</span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(df_merged.isna().<span class="bu">sum</span>())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>1. Extracting electricity consumption data...
2. Extracting weather data (Site: Panther)...
3. Merging time series...

Dataset shape: 17544 hourly observations $\times$ 9 features

--- Data Quality Report (Missing Values) ---
meter_reading      3531
airTemperature        3
cloudCoverage      7542
dewTemperature        3
precipDepth1HR        9
precipDepth6HR    16898
seaLvlPressure      323
windDirection       499
windSpeed             0
dtype: int64</code></pre>
</div>
</div>
</section>
<section id="stage-2-exploratory-data-analysis-eda-and-missing-data-handling" class="level2">
<h2 class="anchored" data-anchor-id="stage-2-exploratory-data-analysis-eda-and-missing-data-handling">Stage 2: Exploratory Data Analysis (EDA) and Missing Data Handling</h2>
<section id="data-quality-assessment-and-cleaning-strategy" class="level3">
<h3 class="anchored" data-anchor-id="data-quality-assessment-and-cleaning-strategy">Data Quality Assessment and Cleaning Strategy</h3>
<p>The initial analysis of the merged dataset reveals three distinct patterns of missing values. Each requires a dedicated preprocessing strategy to ensure the reliability of the predictive model.</p>
<section id="irrecoverable-features-to-be-removed" class="level4">
<h4 class="anchored" data-anchor-id="irrecoverable-features-to-be-removed">1. Irrecoverable Features (<em>To Be Removed</em>)</h4>
<p>The variables <strong><code>precipDepth6HR</code></strong> (16,898 missing values) and <strong><code>cloudCoverage</code></strong> (7,542 missing values) exhibit prohibitively high missing rates (approximately 40% to 90% of the dataset). Imputing these variables would effectively generate synthetic weather observations, introducing significant uncertainty into the model. The most robust approach is therefore to remove these features from the dataset.</p>
</section>
<section id="sparse-missing-values-in-exogenous-variables-to-be-interpolated" class="level4">
<h4 class="anchored" data-anchor-id="sparse-missing-values-in-exogenous-variables-to-be-interpolated">2. Sparse Missing Values in Exogenous Variables (<em>To Be Interpolated</em>)</h4>
<p>Meteorological variables such as <strong><code>airTemperature</code></strong>, <strong><code>dewTemperature</code></strong>, <strong><code>seaLvlPressure</code></strong>, and <strong><code>windDirection</code></strong> contain only a small number of isolated missing values (between 3 and 499 observations). Since these physical quantities evolve smoothly over time, linear time-based interpolation is a reasonable and well-justified preprocessing technique that preserves the underlying temporal dynamics without introducing noticeable distortions.</p>
</section>
<section id="the-critical-variable-energy-consumption-meter_reading" class="level4">
<h4 class="anchored" data-anchor-id="the-critical-variable-energy-consumption-meter_reading">3. The Critical Variable: Energy Consumption (<em><code>meter_reading</code></em>)</h4>
<p>The building’s electricity consumption (<strong><code>meter_reading</code></strong>), which serves as the target variable (ground truth), contains 3,531 missing values (approximately 20% of the dataset). Blindly interpolating the target variable is generally discouraged in supervised learning. If these missing values correspond to an extended sensor outage lasting weeks or months, interpolation would create an artificial signal that does not reflect the building’s true thermal behavior. Consequently, the neural network could learn the interpolation artifact instead of the underlying thermal dynamics.</p>
</section>
<section id="next-step" class="level4">
<h4 class="anchored" data-anchor-id="next-step">Next Step</h4>
<p>Before deciding whether to impute or discard these observations, a visual temporal analysis is required to identify the distribution and duration of the electricity meter outages.</p>
<div id="b99355cd" class="cell" data-execution_count="3">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"1. Cleaning exogenous variables (weather data)..."</span>)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove features with excessive missing values</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>df_merged.drop(columns<span class="op">=</span>[<span class="st">"precipDepth6HR"</span>, <span class="st">"cloudCoverage"</span>], inplace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Linear time interpolation to preserve signal continuity</span></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>cols_to_interpolate <span class="op">=</span> [<span class="st">"airTemperature"</span>, <span class="st">"dewTemperature"</span>, <span class="st">"seaLvlPressure"</span>, <span class="st">"windDirection"</span>, <span class="st">"precipDepth1HR"</span>]</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>df_merged[cols_to_interpolate] <span class="op">=</span> df_merged[cols_to_interpolate].interpolate(method<span class="op">=</span><span class="st">"linear"</span>, limit_direction<span class="op">=</span><span class="st">"both"</span>)</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Missing values after weather data interpolation:"</span>)</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(df_merged.isna().<span class="bu">sum</span>())</span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">2. Visual diagnosis of the target variable (meter_reading)..."</span>)</span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualize the temporal distribution of missing meter readings</span></span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">15</span>, <span class="dv">3</span>))</span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a>df_merged[<span class="st">"meter_reading"</span>].isna().astype(<span class="bu">int</span>).plot( color<span class="op">=</span><span class="st">"red"</span>, linewidth<span class="op">=</span><span class="fl">1.5</span>)</span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-21"><a href="#cb7-21" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Missing Energy Consumption Data (Red = Sensor Outage)"</span>)</span>
<span id="cb7-22"><a href="#cb7-22" aria-hidden="true" tabindex="-1"></a>plt.yticks([<span class="dv">0</span>, <span class="dv">1</span>], [<span class="st">"Available"</span>, <span class="st">"Missing"</span>])</span>
<span id="cb7-23"><a href="#cb7-23" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Time"</span>)</span>
<span id="cb7-24"><a href="#cb7-24" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb7-25"><a href="#cb7-25" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>1. Cleaning exogenous variables (weather data)...
Missing values after weather data interpolation:
meter_reading     3531
airTemperature       0
dewTemperature       0
precipDepth1HR       0
seaLvlPressure       0
windDirection        0
windSpeed            0
dtype: int64

2. Visual diagnosis of the target variable (meter_reading)...</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="optitherm_files/figure-html/cell-4-output-2.png" width="1432" height="279" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="temporal-diagnosis-and-target-variable-handling" class="level4">
<h4 class="anchored" data-anchor-id="temporal-diagnosis-and-target-variable-handling">Temporal Diagnosis and Target Variable Handling</h4>
<p>The temporal analysis reveals a complete absence of energy consumption data from January to the end of May 2016, as well as several shorter missing-data periods, including a prolonged sensor outage of approximately one week during the summer of 2017.</p>
<p>The extended data gap observed at the beginning of the dataset was removed, as the lack of observations over several months prevents any reliable reconstruction of the building’s thermal behavior. In contrast, shorter missing periods were handled through linear time interpolation, which preserves the continuity of the energy consumption signal without introducing significant distortions.</p>
<p>Interestingly, the prolonged sensor outage observed during the summer of 2017 was retained and used as a natural temporal boundary between the training and testing datasets. This approach avoids arbitrary data splitting strategies and ensures a realistic evaluation scenario, where the model is trained on past observations and tested on future unseen conditions.</p>
<p><strong>Methodological justification:</strong></p>
<p>The thermal dynamics of a building are learned from temporal sequences using recurrent neural networks (RNN/LSTM) with sliding windows. Therefore, preserving the chronological structure of the data is essential. By using the sensor outage as a natural separation point, the model evaluation better reflects a real-world deployment scenario, where future energy consumption must be predicted based solely on historical information.</p>
<div id="80b6ca6f" class="cell" data-execution_count="4">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"1. Removing the initial data gap (early 2016)..."</span>)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove the period with insufficient data coverage</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>df_merged <span class="op">=</span> df_merged.loc[<span class="st">"2016-06-01"</span>:]</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"2. Target variable interpolation (strict limit)..."</span>)</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Interpolate only short missing periods (&lt;= 6 hours).</span></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a><span class="co"># The extended summer 2017 outage is intentionally preserved as missing data.</span></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>df_merged[<span class="st">"meter_reading"</span>] <span class="op">=</span> df_merged[<span class="st">"meter_reading"</span>].interpolate(method<span class="op">=</span><span class="st">"linear"</span>, limit<span class="op">=</span><span class="dv">6</span>)</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">--- Final Data Quality Report ---"</span>)</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Dataset size: </span><span class="sc">{</span>df_merged<span class="sc">.</span>shape[<span class="dv">0</span>]<span class="sc">}</span><span class="ss"> hourly observations."</span>)</span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Remaining missing values (corresponding to the summer 2017 outage):"</span>)</span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(df_merged.isna().<span class="bu">sum</span>())</span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">3. Visual diagnosis of the target variable (meter_reading)..."</span>)</span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualize the temporal distribution of remaining missing values</span></span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">15</span>, <span class="dv">3</span>))</span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a>df_merged[<span class="st">"meter_reading"</span>].isna().astype(<span class="bu">int</span>).plot(color<span class="op">=</span><span class="st">"red"</span>, linewidth<span class="op">=</span><span class="fl">1.5</span>)</span>
<span id="cb9-22"><a href="#cb9-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-23"><a href="#cb9-23" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Missing Energy Consumption Data (Red = Sensor Outage)"</span>)</span>
<span id="cb9-24"><a href="#cb9-24" aria-hidden="true" tabindex="-1"></a>plt.yticks([<span class="dv">0</span>, <span class="dv">1</span>], [<span class="st">"Available"</span>, <span class="st">"Missing"</span>])</span>
<span id="cb9-25"><a href="#cb9-25" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Time"</span>)</span>
<span id="cb9-26"><a href="#cb9-26" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb9-27"><a href="#cb9-27" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>1. Removing the initial data gap (early 2016)...
2. Target variable interpolation (strict limit)...

--- Final Data Quality Report ---
Dataset size: 13896 hourly observations.
Remaining missing values (corresponding to the summer 2017 outage):
meter_reading     135
airTemperature      0
dewTemperature      0
precipDepth1HR      0
seaLvlPressure      0
windDirection       0
windSpeed           0
dtype: int64

3. Visual diagnosis of the target variable (meter_reading)...</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="optitherm_files/figure-html/cell-5-output-2.png" width="1432" height="279" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="visual-validation-of-the-temporal-splitting-strategy" class="level4">
<h4 class="anchored" data-anchor-id="visual-validation-of-the-temporal-splitting-strategy">Visual Validation of the Temporal Splitting Strategy</h4>
<p>The final missing-data profile confirms the effectiveness of the preprocessing strategy. The time series now starts consistently in June 2016, and the only remaining discontinuity corresponds to the prolonged sensor outage observed during the summer of 2017.</p>
<p>This temporal gap provides a natural boundary between the training and testing periods, ensuring that the model is evaluated on future unseen data while preserving the chronological structure of the problem. By avoiding artificial data reconstruction in this region, the predictive model is trained and validated on physically consistent energy consumption patterns, preventing potential biases caused by unrealistic interpolated signals.</p>
</section>
<section id="temporal-feature-engineering" class="level4">
<h4 class="anchored" data-anchor-id="temporal-feature-engineering">Temporal Feature Engineering</h4>
<p>Now that the dataset has been cleaned and validated, the next challenge is to represent time in a way that is meaningful for the neural network.</p>
<p>If the hour of the day is provided as a raw numerical value (from 0 to 23), a machine learning model will incorrectly interpret the temporal distance between 23:00 and 00:00 as large (23 units), even though these two timestamps are only one hour apart in the daily cycle.</p>
<p>To overcome this artificial discontinuity, linear temporal variables are projected onto a continuous periodic space using sine and cosine transformations. This elegant representation maps each temporal coordinate onto the unit circle, preserving the natural proximity between the end and the beginning of each cycle.</p>
<p><strong><em>Why use both sine and cosine components?</em></strong></p>
<p>Using only one trigonometric function introduces ambiguity due to symmetry. For example, if only the sine component is used, midnight (<span class="math inline">\(\sin(0)=0\)</span>) and noon (<span class="math inline">\(\sin(\pi)=0\)</span>) would receive the same value, preventing the model from distinguishing between day and night. By combining the cosine component (<span class="math inline">\(X\)</span>-axis) and sine component (<span class="math inline">\(Y\)</span>-axis), each timestamp is uniquely represented in a two-dimensional periodic space. Consequently, the Euclidean distance between 23:00 and 01:00 is correctly interpreted as small by the neural network.</p>
<p>The following code adds these temporal coordinates to the dataset:</p>
<div id="b4e29ead" class="cell" data-execution_count="5">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"1. Applying cyclical time encoding..."</span>)</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Hour of the day (period = 24)</span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>df_merged[<span class="st">"hour_sin"</span>] <span class="op">=</span> np.sin(<span class="dv">2</span> <span class="op">*</span> np.pi <span class="op">*</span> df_merged.index.hour <span class="op">/</span> <span class="fl">24.0</span>)</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>df_merged[<span class="st">"hour_cos"</span>] <span class="op">=</span> np.cos(<span class="dv">2</span> <span class="op">*</span> np.pi <span class="op">*</span> df_merged.index.hour <span class="op">/</span> <span class="fl">24.0</span>)</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Day of the week (period = 7)</span></span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>df_merged[<span class="st">"day_sin"</span>] <span class="op">=</span> np.sin(<span class="dv">2</span> <span class="op">*</span> np.pi <span class="op">*</span> df_merged.index.dayofweek <span class="op">/</span> <span class="fl">7.0</span>)</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>df_merged[<span class="st">"day_cos"</span>] <span class="op">=</span> np.cos(<span class="dv">2</span> <span class="op">*</span> np.pi <span class="op">*</span> df_merged.index.dayofweek <span class="op">/</span> <span class="fl">7.0</span>)</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Wind direction (period = 360)</span></span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a>df_merged[<span class="st">"wind_sin"</span>] <span class="op">=</span> np.sin(<span class="dv">2</span> <span class="op">*</span> np.pi <span class="op">*</span> df_merged[<span class="st">"windDirection"</span>] <span class="op">/</span> <span class="fl">360.0</span>)</span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a>df_merged[<span class="st">"wind_cos"</span>] <span class="op">=</span> np.cos(<span class="dv">2</span> <span class="op">*</span> np.pi <span class="op">*</span> df_merged[<span class="st">"windDirection"</span>] <span class="op">/</span> <span class="fl">360.0</span>)</span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a>df_merged.drop(columns<span class="op">=</span>[<span class="st">"windDirection"</span>], inplace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb11-19"><a href="#cb11-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-20"><a href="#cb11-20" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"2. Visual validation: Hourly phase space representation..."</span>)</span>
<span id="cb11-21"><a href="#cb11-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-22"><a href="#cb11-22" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">8</span>, <span class="dv">6</span>))</span>
<span id="cb11-23"><a href="#cb11-23" aria-hidden="true" tabindex="-1"></a>plt.scatter( df_merged[<span class="st">"hour_cos"</span>], df_merged[<span class="st">"hour_sin"</span>], c<span class="op">=</span>df_merged.index.hour, s<span class="op">=</span><span class="dv">100</span>, cmap<span class="op">=</span><span class="st">"twilight"</span>, edgecolor<span class="op">=</span><span class="st">"k"</span>)</span>
<span id="cb11-24"><a href="#cb11-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-25"><a href="#cb11-25" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Cyclical Encoding: Trigonometric Clock Representation"</span>)</span>
<span id="cb11-26"><a href="#cb11-26" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"hour_cos (Y)"</span>)</span>
<span id="cb11-27"><a href="#cb11-27" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"hour_sin (X)"</span>)</span>
<span id="cb11-28"><a href="#cb11-28" aria-hidden="true" tabindex="-1"></a>plt.colorbar(label<span class="op">=</span><span class="st">"Hour of the day"</span>)</span>
<span id="cb11-29"><a href="#cb11-29" aria-hidden="true" tabindex="-1"></a>plt.grid(<span class="va">True</span>)</span>
<span id="cb11-30"><a href="#cb11-30" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb11-31"><a href="#cb11-31" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>1. Applying cyclical time encoding...
2. Visual validation: Hourly phase space representation...</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="optitherm_files/figure-html/cell-6-output-2.png" width="729" height="566" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="feature-analysis-and-selection-correlation-study" class="level4">
<h4 class="anchored" data-anchor-id="feature-analysis-and-selection-correlation-study">Feature Analysis and Selection: Correlation Study</h4>
<p><strong>Objective:</strong> Identify the exogenous (weather-related) and temporal variables that influence the energy consumption dynamics of the <em>Panther_office_Graham</em> building.</p>
<p><strong>Methodology:</strong> The Pearson correlation coefficient (<span class="math inline">\(r \in [-1,1]\)</span>) is used to quantify the strength and direction of the linear relationship between the input features and the target variable (<code>meter_reading</code>).</p>
<ul>
<li>A value close to <span class="math inline">\(1\)</span> or <span class="math inline">\(-1\)</span> indicates a strong positive or negative linear correlation.</li>
<li>A value close to <span class="math inline">\(0\)</span> indicates the absence of a significant linear relationship.</li>
</ul>
<p>This analysis provides valuable insights for feature selection before training the PyTorch model. Variables with limited predictive relevance may be removed to reduce noise and decrease the dimensionality of the input tensors. However, correlation alone does not fully capture the predictive value of a feature, especially in nonlinear time-dependent systems such as building thermal dynamics.</p>
<p><strong>Code: Correlation Heatmap</strong></p>
<p>The following visualization uses the <code>seaborn</code> library to generate a correlation heatmap, providing an overview of the relationships between the selected features and the energy consumption target.</p>
<div id="ff7455d1" class="cell" data-execution_count="6">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Calculating the Pearson correlation matrix..."</span>)</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute the correlation of all variables with each other</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>corr_matrix <span class="op">=</span> df_merged.corr()</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Isolate specifically the correlations with respect to our target variable</span></span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>target_corr <span class="op">=</span> corr_matrix[[<span class="st">'meter_reading'</span>]].sort_values(by<span class="op">=</span><span class="st">'meter_reading'</span>, ascending<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">--- Correlations with electricity consumption ---"</span>)</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(target_corr)</span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Generating the global Heatmap..."</span>)</span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">8</span>))</span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a><span class="co"># The cmap='coolwarm' parameter helps contrast positive (red) and negative (blue) correlations well</span></span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a>sns.heatmap(corr_matrix, annot<span class="op">=</span><span class="va">True</span>, fmt<span class="op">=</span><span class="st">".2f"</span>, cmap<span class="op">=</span><span class="st">"coolwarm"</span>, vmin<span class="op">=-</span><span class="dv">1</span>, vmax<span class="op">=</span><span class="dv">1</span>, square<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb13-17"><a href="#cb13-17" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Correlation Matrix of Graham Building Variables"</span>)</span>
<span id="cb13-18"><a href="#cb13-18" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb13-19"><a href="#cb13-19" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Calculating the Pearson correlation matrix...

--- Correlations with electricity consumption ---
                meter_reading
meter_reading        1.000000
airTemperature       0.332953
windSpeed            0.316664
day_sin              0.228865
wind_sin             0.082483
seaLvlPressure       0.034707
precipDepth1HR       0.010033
day_cos             -0.015975
wind_cos            -0.091593
dewTemperature      -0.106052
hour_sin            -0.284356
hour_cos            -0.679665

Generating the global Heatmap...</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="optitherm_files/figure-html/cell-7-output-2.png" width="866" height="764" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="pearson-correlation-analysis" class="level4">
<h4 class="anchored" data-anchor-id="pearson-correlation-analysis">Pearson Correlation Analysis</h4>
<p>The Pearson correlation matrix provides an initial overview of the linear relationships between the input features and the building’s electricity consumption.</p>
<p>The results highlight the dominant influence of temporal variables on energy demand. In particular, the daily cyclical components exhibit the strongest correlations, with <code>hour_cos</code> reaching a correlation coefficient of approximately -0.68 and <code>hour_sin</code> a value of -0.28. This confirms the strong daily periodicity of the building’s energy consumption, which is likely driven by occupancy patterns and HVAC operating schedules.</p>
<p>Among the weather-related variables, <code>airTemperature</code> and <code>windSpeed</code> show the strongest linear relationships with electricity consumption, with correlation coefficients of approximately 0.33 and 0.32, respectively. These results are consistent with the expected influence of outdoor conditions on heating and cooling demand.</p>
<p>Conversely, several variables such as <code>seaLvlPressure</code>, <code>precipDepth1HR</code>, <code>wind_sin</code>, and <code>wind_cos</code> exhibit weak instantaneous correlations with the target variable. However, in a thermally dynamic system such as a building, the impact of external conditions is not necessarily immediate. Due to thermal inertia, weather variations may affect energy consumption only after several hours. Consequently, a low instantaneous Pearson correlation does not necessarily indicate that a feature lacks predictive value.</p>
<p>To account for these delayed effects, a lagged Pearson correlation analysis is performed over a 24-hour temporal window. This complementary analysis evaluates whether past values of weakly correlated features contain relevant information about future electricity consumption.</p>
<p>Based on this exploratory analysis, no feature is removed solely based on instantaneous Pearson correlation. Instead, the final feature selection considers a combination of data quality, physical relevance, temporal relationships, and predictive performance during model development.</p>
</section>
<section id="lagged-correlation-analysis" class="level4">
<h4 class="anchored" data-anchor-id="lagged-correlation-analysis">Lagged Correlation Analysis</h4>
<p>Since building energy consumption is governed by thermal inertia and delayed responses to external conditions, features with weak instantaneous correlations were further investigated using a lagged Pearson correlation analysis.</p>
<p>The following variables were selected for this additional analysis based on their limited instantaneous correlation with the target variable:</p>
<ul>
<li><code>wind_sin</code> and <code>wind_cos</code>: cyclic representations of wind direction;</li>
<li><code>seaLvlPressure</code>: atmospheric pressure;</li>
<li><code>precipDepth1HR</code>: short-term precipitation measurements;</li>
<li><code>day_cos</code>: weekly temporal encoding component.</li>
</ul>
<p>The objective is to determine whether past values of these variables contain predictive information about future electricity consumption over a 24-hour horizon. This analysis helps identify delayed relationships that cannot be captured by a standard Pearson correlation computed at the same timestamp.</p>
<div id="f0b7cf53" class="cell" data-execution_count="7">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> compute_lagged_correlation(df, feature, target<span class="op">=</span><span class="st">"meter_reading"</span>, max_lag<span class="op">=</span><span class="dv">24</span>):</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a><span class="co">    Compute Pearson correlation between a feature and the target</span></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a><span class="co">    for different time lags.</span></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a><span class="co">    </span></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a><span class="co">    Positive lag means that past feature values are correlated</span></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a><span class="co">    with future target values.</span></span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>    correlations <span class="op">=</span> {}</span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> lag <span class="kw">in</span> <span class="bu">range</span>(max_lag <span class="op">+</span> <span class="dv">1</span>):</span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a>        shifted_feature <span class="op">=</span> df[feature].shift(lag)</span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a>        correlations[lag] <span class="op">=</span> shifted_feature.corr(df[target])</span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> pd.Series(correlations)</span>
<span id="cb15-19"><a href="#cb15-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-20"><a href="#cb15-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-21"><a href="#cb15-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Variables to investigate</span></span>
<span id="cb15-22"><a href="#cb15-22" aria-hidden="true" tabindex="-1"></a>features_to_test <span class="op">=</span> [</span>
<span id="cb15-23"><a href="#cb15-23" aria-hidden="true" tabindex="-1"></a>    <span class="st">"wind_cos"</span>,</span>
<span id="cb15-24"><a href="#cb15-24" aria-hidden="true" tabindex="-1"></a>    <span class="st">"wind_sin"</span>,</span>
<span id="cb15-25"><a href="#cb15-25" aria-hidden="true" tabindex="-1"></a>    <span class="st">"day_cos"</span>,</span>
<span id="cb15-26"><a href="#cb15-26" aria-hidden="true" tabindex="-1"></a>    <span class="st">"seaLvlPressure"</span>,</span>
<span id="cb15-27"><a href="#cb15-27" aria-hidden="true" tabindex="-1"></a>    <span class="st">"precipDepth1HR"</span></span>
<span id="cb15-28"><a href="#cb15-28" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb15-29"><a href="#cb15-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-30"><a href="#cb15-30" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"--- Lagged Pearson Correlations (24h window) ---"</span>)</span>
<span id="cb15-31"><a href="#cb15-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-32"><a href="#cb15-32" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">6</span>))</span>
<span id="cb15-33"><a href="#cb15-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-34"><a href="#cb15-34" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> feature <span class="kw">in</span> features_to_test:</span>
<span id="cb15-35"><a href="#cb15-35" aria-hidden="true" tabindex="-1"></a>    lag_corr <span class="op">=</span> compute_lagged_correlation(</span>
<span id="cb15-36"><a href="#cb15-36" aria-hidden="true" tabindex="-1"></a>        df_merged,</span>
<span id="cb15-37"><a href="#cb15-37" aria-hidden="true" tabindex="-1"></a>        feature,</span>
<span id="cb15-38"><a href="#cb15-38" aria-hidden="true" tabindex="-1"></a>        target<span class="op">=</span><span class="st">"meter_reading"</span>,</span>
<span id="cb15-39"><a href="#cb15-39" aria-hidden="true" tabindex="-1"></a>        max_lag<span class="op">=</span><span class="dv">24</span>,</span>
<span id="cb15-40"><a href="#cb15-40" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb15-41"><a href="#cb15-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-42"><a href="#cb15-42" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="sc">{</span>feature<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb15-43"><a href="#cb15-43" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(lag_corr.sort_values(key<span class="op">=</span><span class="bu">abs</span>, ascending<span class="op">=</span><span class="va">False</span>).head(<span class="dv">5</span>))</span>
<span id="cb15-44"><a href="#cb15-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-45"><a href="#cb15-45" aria-hidden="true" tabindex="-1"></a>    plt.plot(</span>
<span id="cb15-46"><a href="#cb15-46" aria-hidden="true" tabindex="-1"></a>        lag_corr.index,</span>
<span id="cb15-47"><a href="#cb15-47" aria-hidden="true" tabindex="-1"></a>        lag_corr.values,</span>
<span id="cb15-48"><a href="#cb15-48" aria-hidden="true" tabindex="-1"></a>        marker<span class="op">=</span><span class="st">"o"</span>,</span>
<span id="cb15-49"><a href="#cb15-49" aria-hidden="true" tabindex="-1"></a>        label<span class="op">=</span>feature,</span>
<span id="cb15-50"><a href="#cb15-50" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb15-51"><a href="#cb15-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-52"><a href="#cb15-52" aria-hidden="true" tabindex="-1"></a>plt.axhline(<span class="dv">0</span>, linestyle<span class="op">=</span><span class="st">"--"</span>)</span>
<span id="cb15-53"><a href="#cb15-53" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Lag (hours)"</span>)</span>
<span id="cb15-54"><a href="#cb15-54" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Pearson correlation"</span>)</span>
<span id="cb15-55"><a href="#cb15-55" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Lagged Correlation Between Weather Variables and Energy Consumption"</span>)</span>
<span id="cb15-56"><a href="#cb15-56" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb15-57"><a href="#cb15-57" aria-hidden="true" tabindex="-1"></a>plt.grid(<span class="va">True</span>)</span>
<span id="cb15-58"><a href="#cb15-58" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb15-59"><a href="#cb15-59" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>--- Lagged Pearson Correlations (24h window) ---

wind_cos
10    0.135799
9     0.132265
11    0.131421
8     0.123380
12    0.120812
dtype: float64

wind_sin
20    0.135305
21    0.134509
19    0.130162
22    0.126679
18    0.123419
dtype: float64

day_cos
24    0.168843
23    0.167962
22    0.166774
21    0.164763
20    0.162125
dtype: float64

seaLvlPressure
9     0.106252
10    0.103067
8     0.100437
11    0.090618
7     0.088409
dtype: float64

precipDepth1HR
9    -0.072556
10   -0.070348
8    -0.069569
11   -0.067131
7    -0.063401
dtype: float64</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="optitherm_files/figure-html/cell-8-output-2.png" width="952" height="566" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>The results reveal that several variables exhibit weak but non-zero delayed relationships with the target variable. The cyclic wind components (<code>wind_sin</code> and <code>wind_cos</code>) show maximum correlations around 10 to 21 hours ahead, with coefficients of approximately 0.13. This suggests that wind conditions may have a delayed influence on energy consumption, potentially through their effect on building envelope heat transfer and air infiltration. However, the magnitude of this correlation remains limited.</p>
<p>The weekly temporal encoding variable <code>day_cos</code> exhibits a stronger delayed correlation, reaching approximately 0.17 after 20–24 hours. This behavior is consistent with the occupancy patterns of office buildings, where energy demand follows recurring weekly schedules.</p>
<p>The atmospheric pressure variable (<code>seaLvlPressure</code>) presents a weak delayed correlation, with a maximum value close to 0.11 around 9 hours. While this indicates a possible relationship with changing weather conditions, its contribution is expected to be limited compared with more direct variables such as outdoor temperature.</p>
<p>Finally, <code>precipDepth1HR</code> shows negligible delayed correlations (below 0.08 in absolute value), suggesting that short-term precipitation information provides limited predictive value for the building’s electricity consumption.</p>
<p>Based on this analysis, <code>day_sin</code> and <code>day_cos</code> are retained as essential temporal features, while wind-related variables and atmospheric pressure are kept for further evaluation during model training. The precipitation variable is excluded due to its limited correlation and expected low predictive contribution.</p>
</section>
</section>
<section id="sequential-data-preparation-and-tensor-construction" class="level3">
<h3 class="anchored" data-anchor-id="sequential-data-preparation-and-tensor-construction">Sequential Data Preparation and Tensor Construction</h3>
<p><strong>Objective:</strong> Transform the cleaned and engineered time series data into three-dimensional sequences suitable for recurrent neural networks. This representation allows the model to capture temporal dependencies and the thermal inertia of the building.</p>
<section id="feature-selection-and-input-space-definition" class="level4">
<h4 class="anchored" data-anchor-id="feature-selection-and-input-space-definition">1. Feature Selection and Input Space Definition</h4>
<p>Following the exploratory analysis, feature selection is performed by combining data quality assessment, physical interpretation, and temporal correlation analysis.</p>
<p>Features with insufficient data availability (<code>cloudCoverage</code> and <code>precipDepth6HR</code>) were removed during the initial preprocessing stage. In addition, <code>precipDepth1HR</code> is excluded after the lagged correlation analysis, as it shows limited instantaneous and delayed relationships with electricity consumption, suggesting a negligible predictive contribution.</p>
<p>Conversely, variables with weak instantaneous correlations but potentially meaningful delayed effects, such as wind-related components (<code>wind_sin</code> and <code>wind_cos</code>), are retained for further evaluation during model training. This approach avoids removing potentially informative features solely based on linear correlation metrics.</p>
<p>The final input space is therefore defined by the combination of physically relevant variables, engineered temporal features, and features supported by the exploratory analysis.</p>
</section>
<section id="chronological-split-and-data-normalization" class="level4">
<h4 class="anchored" data-anchor-id="chronological-split-and-data-normalization">2. Chronological Split and Data Normalization</h4>
<p>The prolonged sensor outage observed during the summer of 2017 provides a natural temporal boundary for separating the datasets. The period preceding this interruption (<code>June 2016 to July 2017</code>) is used for model training, while the subsequent period (<code>August 2017 to December 2017</code>) is reserved for model evaluation.</p>
<p>This chronological split (~75/25) prevents any temporal data leakage and provides a realistic assessment of the model’s ability to generalize to unseen seasonal conditions, particularly during the transition toward autumn and winter.</p>
<p>All input variables are normalized using Min-Max scaling. Importantly, the scaling parameters are fitted exclusively on the training set and then applied to the validation/test set to preserve the integrity of the evaluation process.</p>
</section>
<section id="sliding-window-sequence-generation" class="level4">
<h4 class="anchored" data-anchor-id="sliding-window-sequence-generation">3. Sliding Window Sequence Generation</h4>
<p>Recurrent neural networks require sequential inputs to learn temporal dependencies. The time series is therefore transformed into overlapping sequences of fixed length.</p>
<p>The resulting input tensors have the following dimensions:</p>
<p>[ (N, L, F) ]</p>
<p>where:</p>
<ul>
<li><span class="math inline">\(N\)</span> is the number of generated samples;</li>
<li><span class="math inline">\(L\)</span> is the sequence length (<span class="math inline">\(L=24\)</span> hours);</li>
<li><span class="math inline">\(F\)</span> is the number of input features.</li>
</ul>
<p>To predict the energy consumption at time <span class="math inline">\(t\)</span>, the model receives the previous 24 hours of system information:</p>
<p>[ [X_{t-24}, X_{t-23}, …, X_{t-1}] ]</p>
<p>Any sequence containing missing target values is discarded to ensure that the model is trained only on physically consistent observations.</p>
<div id="cceca014" class="cell" data-execution_count="8">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.preprocessing <span class="im">import</span> MinMaxScaler</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"1. Definition of the model feature space..."</span>)</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Features removed after data quality and correlation analysis</span></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>cols_to_drop <span class="op">=</span> [</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">'precipDepth1HR'</span>,</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>    <span class="co">#'seaLvlPressure'</span></span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a>df_model <span class="op">=</span> df_merged.drop(columns<span class="op">=</span>cols_to_drop).copy()</span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Remaining features: </span><span class="sc">{</span>df_model<span class="sc">.</span>columns<span class="sc">.</span>tolist()<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-17"><a href="#cb17-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">2. Chronological train/test split using the natural sensor outage..."</span>)</span>
<span id="cb17-18"><a href="#cb17-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-19"><a href="#cb17-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Detect the remaining missing target values corresponding to the sensor outage</span></span>
<span id="cb17-20"><a href="#cb17-20" aria-hidden="true" tabindex="-1"></a>nan_indices <span class="op">=</span> df_model[df_model[<span class="st">'meter_reading'</span>].isna()].index</span>
<span id="cb17-21"><a href="#cb17-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-22"><a href="#cb17-22" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> <span class="bu">len</span>(nan_indices) <span class="op">&gt;</span> <span class="dv">0</span>:</span>
<span id="cb17-23"><a href="#cb17-23" aria-hidden="true" tabindex="-1"></a>    gap_start <span class="op">=</span> nan_indices[<span class="dv">0</span>]</span>
<span id="cb17-24"><a href="#cb17-24" aria-hidden="true" tabindex="-1"></a>    gap_end <span class="op">=</span> nan_indices[<span class="op">-</span><span class="dv">1</span>]</span>
<span id="cb17-25"><a href="#cb17-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-26"><a href="#cb17-26" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"-&gt; Detected outage period: </span><span class="sc">{</span>gap_start<span class="sc">}</span><span class="ss"> to </span><span class="sc">{</span>gap_end<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb17-27"><a href="#cb17-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-28"><a href="#cb17-28" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Training set: data before the outage</span></span>
<span id="cb17-29"><a href="#cb17-29" aria-hidden="true" tabindex="-1"></a>    df_train <span class="op">=</span> df_model.loc[:gap_start <span class="op">-</span> pd.Timedelta(hours<span class="op">=</span><span class="dv">1</span>)].copy()</span>
<span id="cb17-30"><a href="#cb17-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-31"><a href="#cb17-31" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Test set: data after the outage</span></span>
<span id="cb17-32"><a href="#cb17-32" aria-hidden="true" tabindex="-1"></a>    df_test <span class="op">=</span> df_model.loc[gap_end <span class="op">+</span> pd.Timedelta(hours<span class="op">=</span><span class="dv">1</span>):].copy()</span>
<span id="cb17-33"><a href="#cb17-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-34"><a href="#cb17-34" aria-hidden="true" tabindex="-1"></a><span class="cf">else</span>:</span>
<span id="cb17-35"><a href="#cb17-35" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"-&gt; No outage detected. Using an 80/20 chronological split."</span>)</span>
<span id="cb17-36"><a href="#cb17-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-37"><a href="#cb17-37" aria-hidden="true" tabindex="-1"></a>    split_idx <span class="op">=</span> <span class="bu">int</span>(<span class="bu">len</span>(df_model) <span class="op">*</span> <span class="fl">0.8</span>)</span>
<span id="cb17-38"><a href="#cb17-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-39"><a href="#cb17-39" aria-hidden="true" tabindex="-1"></a>    df_train <span class="op">=</span> df_model.iloc[:split_idx].copy()</span>
<span id="cb17-40"><a href="#cb17-40" aria-hidden="true" tabindex="-1"></a>    df_test <span class="op">=</span> df_model.iloc[split_idx:].copy()</span>
<span id="cb17-41"><a href="#cb17-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-42"><a href="#cb17-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-43"><a href="#cb17-43" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"-&gt; Training samples: </span><span class="sc">{</span><span class="bu">len</span>(df_train)<span class="sc">}</span><span class="ss"> hours"</span>)</span>
<span id="cb17-44"><a href="#cb17-44" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"-&gt; Testing samples : </span><span class="sc">{</span><span class="bu">len</span>(df_test)<span class="sc">}</span><span class="ss"> hours"</span>)</span>
<span id="cb17-45"><a href="#cb17-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-46"><a href="#cb17-46" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">3. Min-Max normalization (training data only)..."</span>)</span>
<span id="cb17-47"><a href="#cb17-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-48"><a href="#cb17-48" aria-hidden="true" tabindex="-1"></a>scaler_X <span class="op">=</span> MinMaxScaler()</span>
<span id="cb17-49"><a href="#cb17-49" aria-hidden="true" tabindex="-1"></a>scaler_y <span class="op">=</span> MinMaxScaler()</span>
<span id="cb17-50"><a href="#cb17-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-51"><a href="#cb17-51" aria-hidden="true" tabindex="-1"></a>target_col <span class="op">=</span> <span class="st">'meter_reading'</span></span>
<span id="cb17-52"><a href="#cb17-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-53"><a href="#cb17-53" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit only on training data to avoid data leakage</span></span>
<span id="cb17-54"><a href="#cb17-54" aria-hidden="true" tabindex="-1"></a>X_train_scaled <span class="op">=</span> scaler_X.fit_transform(df_train)</span>
<span id="cb17-55"><a href="#cb17-55" aria-hidden="true" tabindex="-1"></a>y_train_scaled <span class="op">=</span> scaler_y.fit_transform(df_train[[target_col]])</span>
<span id="cb17-56"><a href="#cb17-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-57"><a href="#cb17-57" aria-hidden="true" tabindex="-1"></a><span class="co"># Apply the same transformation to unseen data</span></span>
<span id="cb17-58"><a href="#cb17-58" aria-hidden="true" tabindex="-1"></a>X_test_scaled <span class="op">=</span> scaler_X.transform(df_test)</span>
<span id="cb17-59"><a href="#cb17-59" aria-hidden="true" tabindex="-1"></a>y_test_scaled <span class="op">=</span> scaler_y.transform(df_test[[target_col]])</span>
<span id="cb17-60"><a href="#cb17-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-61"><a href="#cb17-61" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-62"><a href="#cb17-62" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">4. Sliding window sequence generation..."</span>)</span>
<span id="cb17-63"><a href="#cb17-63" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-64"><a href="#cb17-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-65"><a href="#cb17-65" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> create_sequences(data_X, data_y, seq_length):</span>
<span id="cb17-66"><a href="#cb17-66" aria-hidden="true" tabindex="-1"></a>    xs, ys <span class="op">=</span> [], []</span>
<span id="cb17-67"><a href="#cb17-67" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-68"><a href="#cb17-68" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="bu">len</span>(data_X) <span class="op">-</span> seq_length):</span>
<span id="cb17-69"><a href="#cb17-69" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-70"><a href="#cb17-70" aria-hidden="true" tabindex="-1"></a>        x_window <span class="op">=</span> data_X[i:i <span class="op">+</span> seq_length]</span>
<span id="cb17-71"><a href="#cb17-71" aria-hidden="true" tabindex="-1"></a>        y_target <span class="op">=</span> data_y[i <span class="op">+</span> seq_length]</span>
<span id="cb17-72"><a href="#cb17-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-73"><a href="#cb17-73" aria-hidden="true" tabindex="-1"></a>        <span class="co"># Remove sequences containing missing values</span></span>
<span id="cb17-74"><a href="#cb17-74" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> <span class="kw">not</span> (np.isnan(x_window).<span class="bu">any</span>() <span class="kw">or</span> np.isnan(y_target).<span class="bu">any</span>()):</span>
<span id="cb17-75"><a href="#cb17-75" aria-hidden="true" tabindex="-1"></a>            xs.append(x_window)</span>
<span id="cb17-76"><a href="#cb17-76" aria-hidden="true" tabindex="-1"></a>            ys.append(y_target)</span>
<span id="cb17-77"><a href="#cb17-77" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-78"><a href="#cb17-78" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> np.array(xs), np.array(ys)</span>
<span id="cb17-79"><a href="#cb17-79" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-80"><a href="#cb17-80" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-81"><a href="#cb17-81" aria-hidden="true" tabindex="-1"></a>SEQUENCE_LENGTH <span class="op">=</span> <span class="dv">24</span></span>
<span id="cb17-82"><a href="#cb17-82" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-83"><a href="#cb17-83" aria-hidden="true" tabindex="-1"></a>X_train_tensor, y_train_tensor <span class="op">=</span> create_sequences(</span>
<span id="cb17-84"><a href="#cb17-84" aria-hidden="true" tabindex="-1"></a>    X_train_scaled,</span>
<span id="cb17-85"><a href="#cb17-85" aria-hidden="true" tabindex="-1"></a>    y_train_scaled,</span>
<span id="cb17-86"><a href="#cb17-86" aria-hidden="true" tabindex="-1"></a>    SEQUENCE_LENGTH</span>
<span id="cb17-87"><a href="#cb17-87" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb17-88"><a href="#cb17-88" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-89"><a href="#cb17-89" aria-hidden="true" tabindex="-1"></a>X_test_tensor, y_test_tensor <span class="op">=</span> create_sequences(</span>
<span id="cb17-90"><a href="#cb17-90" aria-hidden="true" tabindex="-1"></a>    X_test_scaled,</span>
<span id="cb17-91"><a href="#cb17-91" aria-hidden="true" tabindex="-1"></a>    y_test_scaled,</span>
<span id="cb17-92"><a href="#cb17-92" aria-hidden="true" tabindex="-1"></a>    SEQUENCE_LENGTH</span>
<span id="cb17-93"><a href="#cb17-93" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb17-94"><a href="#cb17-94" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-95"><a href="#cb17-95" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">--- Tensor Summary ---"</span>)</span>
<span id="cb17-96"><a href="#cb17-96" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Training X: </span><span class="sc">{</span>X_train_tensor<span class="sc">.</span>shape<span class="sc">}</span><span class="ss">, y: </span><span class="sc">{</span>y_train_tensor<span class="sc">.</span>shape<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb17-97"><a href="#cb17-97" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Testing X : </span><span class="sc">{</span>X_test_tensor<span class="sc">.</span>shape<span class="sc">}</span><span class="ss">, y: </span><span class="sc">{</span>y_test_tensor<span class="sc">.</span>shape<span class="sc">}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>1. Definition of the model feature space...
Remaining features: ['meter_reading', 'airTemperature', 'dewTemperature', 'seaLvlPressure', 'windSpeed', 'hour_sin', 'hour_cos', 'day_sin', 'day_cos', 'wind_sin', 'wind_cos']

2. Chronological train/test split using the natural sensor outage...
-&gt; Detected outage period: 2017-07-19 01:00:00 to 2017-07-24 15:00:00
-&gt; Training samples: 9913 hours
-&gt; Testing samples : 3848 hours

3. Min-Max normalization (training data only)...

4. Sliding window sequence generation...

--- Tensor Summary ---
Training X: (9889, 24, 11), y: (9889, 1)
Testing X : (3824, 24, 11), y: (3824, 1)</code></pre>
</div>
</div>
</section>
</section>
</section>
<section id="stage-4-thermallstm-architecture-definition" class="level2">
<h2 class="anchored" data-anchor-id="stage-4-thermallstm-architecture-definition">Stage 4: ThermalLSTM Architecture Definition</h2>
<p>With the sequential dataset prepared, the next step is to define the neural network architecture used to learn the building’s thermal dynamics.</p>
<p>The objective of this first deep learning model is to construct a data-driven approximation of the relationship between the recent evolution of the building state and its electricity consumption. Because building energy systems exhibit temporal dependencies caused by thermal inertia, a recurrent neural network architecture based on Long Short-Term Memory (LSTM) units is selected.</p>
<p>The proposed model, named <strong>ThermalLSTM</strong>, is designed as a sequence-to-one regression model. It receives a 24-hour historical sequence of building features and outputs a single prediction corresponding to the electricity consumption at the following time step.</p>
<p>The architecture consists of two main components:</p>
<ol type="1">
<li><p><strong>LSTM recurrent layers</strong></p>
<p>The recurrent block extracts temporal patterns from the input sequence and stores relevant information through hidden and cell states. Stacking multiple LSTM layers allows the model to learn increasingly complex temporal representations of the building dynamics.</p></li>
<li><p><strong>Fully connected projection layer</strong></p>
<p>The final hidden representation is mapped to a single scalar value through a linear layer, providing the predicted electricity consumption.</p></li>
</ol>
<p>The model parameters are optimized by minimizing the Mean Squared Error (MSE) loss, which is appropriate for this continuous regression problem. The Adam optimizer is selected due to its adaptive learning rate mechanism and its robustness for training deep neural networks.</p>
<p>The following code implements the <code>ThermalLSTM</code> architecture and initializes the training configuration.</p>
<div id="55482aea" class="cell" data-execution_count="9">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> torch</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> torch.nn <span class="im">as</span> nn</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> torch.optim <span class="im">as</span> optim</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Defining the ThermalLSTM architecture..."</span>)</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a><span class="kw">class</span> ThermalLSTM(nn.Module):</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>    <span class="co">r"""__init__(input_size, hidden_size, num_layers=1)</span></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a><span class="co">        LSTM-based sequence-to-one model for building energy consumption prediction.</span></span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> <span class="fu">__init__</span>(<span class="va">self</span>, input_size, hidden_size, num_layers<span class="op">=</span><span class="dv">1</span>):</span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>        <span class="bu">super</span>(ThermalLSTM, <span class="va">self</span>).<span class="fu">__init__</span>()</span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.hidden_size <span class="op">=</span> hidden_size</span>
<span id="cb19-17"><a href="#cb19-17" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.num_layers <span class="op">=</span> num_layers</span>
<span id="cb19-18"><a href="#cb19-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-19"><a href="#cb19-19" aria-hidden="true" tabindex="-1"></a>        <span class="co"># Recurrent layers</span></span>
<span id="cb19-20"><a href="#cb19-20" aria-hidden="true" tabindex="-1"></a>        <span class="co"># Input format: (batch, sequence_length, features)</span></span>
<span id="cb19-21"><a href="#cb19-21" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.lstm <span class="op">=</span> nn.LSTM(input_size<span class="op">=</span>input_size, hidden_size<span class="op">=</span>hidden_size, num_layers<span class="op">=</span>num_layers, batch_first<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb19-22"><a href="#cb19-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-23"><a href="#cb19-23" aria-hidden="true" tabindex="-1"></a>        <span class="co"># Projection from hidden representation to energy consumption</span></span>
<span id="cb19-24"><a href="#cb19-24" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.fc <span class="op">=</span> nn.Linear(in_features<span class="op">=</span>hidden_size, out_features<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb19-25"><a href="#cb19-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-26"><a href="#cb19-26" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> forward(<span class="va">self</span>, x):</span>
<span id="cb19-27"><a href="#cb19-27" aria-hidden="true" tabindex="-1"></a>        <span class="co">"""</span></span>
<span id="cb19-28"><a href="#cb19-28" aria-hidden="true" tabindex="-1"></a><span class="co">        Forward propagation.</span></span>
<span id="cb19-29"><a href="#cb19-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-30"><a href="#cb19-30" aria-hidden="true" tabindex="-1"></a><span class="co">        Args:</span></span>
<span id="cb19-31"><a href="#cb19-31" aria-hidden="true" tabindex="-1"></a><span class="co">            x: tensor of shape (batch, sequence_length, features)</span></span>
<span id="cb19-32"><a href="#cb19-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-33"><a href="#cb19-33" aria-hidden="true" tabindex="-1"></a><span class="co">        Returns:</span></span>
<span id="cb19-34"><a href="#cb19-34" aria-hidden="true" tabindex="-1"></a><span class="co">            Predicted energy consumption at the next time step.</span></span>
<span id="cb19-35"><a href="#cb19-35" aria-hidden="true" tabindex="-1"></a><span class="co">        """</span></span>
<span id="cb19-36"><a href="#cb19-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-37"><a href="#cb19-37" aria-hidden="true" tabindex="-1"></a>        <span class="co"># Extract temporal representation</span></span>
<span id="cb19-38"><a href="#cb19-38" aria-hidden="true" tabindex="-1"></a>        out, _ <span class="op">=</span> <span class="va">self</span>.lstm(x)</span>
<span id="cb19-39"><a href="#cb19-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-40"><a href="#cb19-40" aria-hidden="true" tabindex="-1"></a>        <span class="co"># Use the hidden state corresponding to the last observation</span></span>
<span id="cb19-41"><a href="#cb19-41" aria-hidden="true" tabindex="-1"></a>        last_hidden_state <span class="op">=</span> out[:, <span class="op">-</span><span class="dv">1</span>, :]</span>
<span id="cb19-42"><a href="#cb19-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-43"><a href="#cb19-43" aria-hidden="true" tabindex="-1"></a>        <span class="co"># Map hidden representation to scalar prediction</span></span>
<span id="cb19-44"><a href="#cb19-44" aria-hidden="true" tabindex="-1"></a>        prediction <span class="op">=</span> <span class="va">self</span>.fc(last_hidden_state)</span>
<span id="cb19-45"><a href="#cb19-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-46"><a href="#cb19-46" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> prediction</span>
<span id="cb19-47"><a href="#cb19-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-48"><a href="#cb19-48" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb19-49"><a href="#cb19-49" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"1. Initializing ThermalLSTM model..."</span>)</span>
<span id="cb19-50"><a href="#cb19-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-51"><a href="#cb19-51" aria-hidden="true" tabindex="-1"></a>INPUT_SIZE <span class="op">=</span> X_train_tensor.shape[<span class="dv">2</span>]</span>
<span id="cb19-52"><a href="#cb19-52" aria-hidden="true" tabindex="-1"></a>HIDDEN_SIZE <span class="op">=</span> <span class="dv">32</span></span>
<span id="cb19-53"><a href="#cb19-53" aria-hidden="true" tabindex="-1"></a>NUM_LAYERS <span class="op">=</span> <span class="dv">1</span></span>
<span id="cb19-54"><a href="#cb19-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-55"><a href="#cb19-55" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> ThermalLSTM(input_size<span class="op">=</span>INPUT_SIZE, hidden_size<span class="op">=</span>HIDDEN_SIZE, num_layers<span class="op">=</span>NUM_LAYERS)</span>
<span id="cb19-56"><a href="#cb19-56" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(model)</span>
<span id="cb19-57"><a href="#cb19-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-58"><a href="#cb19-58" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">2. Configuring training parameters..."</span>)</span>
<span id="cb19-59"><a href="#cb19-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-60"><a href="#cb19-60" aria-hidden="true" tabindex="-1"></a><span class="co"># Regression loss for continuous energy consumption prediction</span></span>
<span id="cb19-61"><a href="#cb19-61" aria-hidden="true" tabindex="-1"></a>criterion <span class="op">=</span> nn.MSELoss()</span>
<span id="cb19-62"><a href="#cb19-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-63"><a href="#cb19-63" aria-hidden="true" tabindex="-1"></a><span class="co"># Adam optimizer for stable neural network training</span></span>
<span id="cb19-64"><a href="#cb19-64" aria-hidden="true" tabindex="-1"></a>learning_rate <span class="op">=</span> <span class="fl">1e-3</span></span>
<span id="cb19-65"><a href="#cb19-65" aria-hidden="true" tabindex="-1"></a>optimizer <span class="op">=</span> optim.Adam(model.parameters(), lr<span class="op">=</span>learning_rate)</span>
<span id="cb19-66"><a href="#cb19-66" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-67"><a href="#cb19-67" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"-&gt; Learning rate: </span><span class="sc">{</span>learning_rate<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb19-68"><a href="#cb19-68" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"-&gt; Model ready for training."</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Defining the ThermalLSTM architecture...
1. Initializing ThermalLSTM model...
ThermalLSTM(
  (lstm): LSTM(11, 32, batch_first=True)
  (fc): Linear(in_features=32, out_features=1, bias=True)
)

2. Configuring training parameters...
-&gt; Learning rate: 0.001
-&gt; Model ready for training.</code></pre>
</div>
</div>
<div id="1e58cbb1" class="cell" data-execution_count="10">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> torch</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> torch.utils.data <span class="im">import</span> TensorDataset, DataLoader</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Device agnostic</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>device  <span class="op">=</span> <span class="st">"gpu"</span> <span class="cf">if</span> torch.cuda.is_available() <span class="cf">else</span> <span class="st">"mps"</span> <span class="cf">if</span> torch.backends.mps.is_available() <span class="cf">else</span> <span class="st">"cpu"</span></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Selected device: </span><span class="sc">{</span>device<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Data conversion to PyTorch tensors</span></span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Converting NumPy arrays into PyTorch tensors..."</span>)</span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>X_train_t <span class="op">=</span> torch.tensor(X_train_tensor, dtype<span class="op">=</span>torch.float32)</span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>y_train_t <span class="op">=</span> torch.tensor(y_train_tensor, dtype<span class="op">=</span>torch.float32)</span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>X_test_t <span class="op">=</span> torch.tensor(X_test_tensor, dtype<span class="op">=</span>torch.float32)</span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a>y_test_t <span class="op">=</span> torch.tensor(y_test_tensor, dtype<span class="op">=</span>torch.float32)</span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Creating DataLoaders..."</span>)</span>
<span id="cb21-16"><a href="#cb21-16" aria-hidden="true" tabindex="-1"></a>BATCH_SIZE <span class="op">=</span> <span class="dv">64</span></span>
<span id="cb21-17"><a href="#cb21-17" aria-hidden="true" tabindex="-1"></a>train_dataset <span class="op">=</span> TensorDataset(X_train_t, y_train_t)</span>
<span id="cb21-18"><a href="#cb21-18" aria-hidden="true" tabindex="-1"></a>test_dataset <span class="op">=</span> TensorDataset(X_test_t, y_test_t)</span>
<span id="cb21-19"><a href="#cb21-19" aria-hidden="true" tabindex="-1"></a>train_loader <span class="op">=</span> DataLoader(train_dataset, batch_size<span class="op">=</span>BATCH_SIZE, shuffle<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb21-20"><a href="#cb21-20" aria-hidden="true" tabindex="-1"></a>test_loader <span class="op">=</span> DataLoader(test_dataset, batch_size<span class="op">=</span>BATCH_SIZE, shuffle<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb21-21"><a href="#cb21-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-22"><a href="#cb21-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Sending the model to the target device</span></span>
<span id="cb21-23"><a href="#cb21-23" aria-hidden="true" tabindex="-1"></a>model.to(device)</span>
<span id="cb21-24"><a href="#cb21-24" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"-&gt; Training batches per epoch: </span><span class="sc">{</span><span class="bu">len</span>(train_loader)<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb21-25"><a href="#cb21-25" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"-&gt; Model running on: </span><span class="sc">{</span>device<span class="sc">}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Selected device: cpu

Converting NumPy arrays into PyTorch tensors...

Creating DataLoaders...
-&gt; Training batches per epoch: 155
-&gt; Model running on: cpu</code></pre>
</div>
</div>
</section>
<section id="stage-5-thermallstm-training-and-model-optimization" class="level2">
<h2 class="anchored" data-anchor-id="stage-5-thermallstm-training-and-model-optimization">Stage 5: ThermalLSTM Training and Model Optimization</h2>
<p>After defining the architecture and preparing the sequential data loaders, the ThermalLSTM model is trained to learn the relationship between historical building states and future electricity consumption.</p>
<p>The training process follows a supervised learning strategy based on gradient descent. For each batch of sequences, the model performs a forward propagation to estimate the energy consumption, the Mean Squared Error (MSE) loss is computed, and the network parameters are updated through backpropagation using the Adam optimizer.</p>
<p>The training procedure is organized into two phases:</p>
<ol type="1">
<li><p><strong>Training phase</strong></p>
<p>The model parameters are updated using the training sequences. The optimizer minimizes the prediction error by iteratively adjusting the LSTM weights.</p></li>
<li><p><strong>Evaluation phase</strong></p>
<p>After each epoch, the model is evaluated on the future unseen dataset separated by the natural sensor outage boundary. This chronological evaluation provides a realistic measure of the model’s generalization capability.</p></li>
</ol>
<p>The evolution of the training and evaluation losses is stored throughout the optimization process to monitor convergence and detect potential overfitting.</p>
<div id="7510d142" class="cell" data-execution_count="11">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> torch</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Configuring the training loop..."</span>)</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>EPOCHS <span class="op">=</span> <span class="dv">200</span></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>PRINT_FREQ <span class="op">=</span> <span class="dv">10</span></span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>train_losses <span class="op">=</span> []</span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>test_losses <span class="op">=</span> []</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>best_test_loss <span class="op">=</span> <span class="bu">float</span>(<span class="st">"inf"</span>)</span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>best_model_state <span class="op">=</span> <span class="va">None</span></span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> epoch <span class="kw">in</span> <span class="bu">range</span>(EPOCHS):</span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a>    <span class="co">### Training phase</span></span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a>    model.train()</span>
<span id="cb23-16"><a href="#cb23-16" aria-hidden="true" tabindex="-1"></a>    running_train_loss <span class="op">=</span> <span class="fl">0.0</span></span>
<span id="cb23-17"><a href="#cb23-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-18"><a href="#cb23-18" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> X_batch, y_batch <span class="kw">in</span> train_loader:</span>
<span id="cb23-19"><a href="#cb23-19" aria-hidden="true" tabindex="-1"></a>        X_batch, y_batch <span class="op">=</span> X_batch.to(device), y_batch.to(device)</span>
<span id="cb23-20"><a href="#cb23-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-21"><a href="#cb23-21" aria-hidden="true" tabindex="-1"></a>        <span class="co"># Reset gradients</span></span>
<span id="cb23-22"><a href="#cb23-22" aria-hidden="true" tabindex="-1"></a>        optimizer.zero_grad()</span>
<span id="cb23-23"><a href="#cb23-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-24"><a href="#cb23-24" aria-hidden="true" tabindex="-1"></a>        <span class="co"># Forward pass</span></span>
<span id="cb23-25"><a href="#cb23-25" aria-hidden="true" tabindex="-1"></a>        predictions <span class="op">=</span> model(X_batch)</span>
<span id="cb23-26"><a href="#cb23-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-27"><a href="#cb23-27" aria-hidden="true" tabindex="-1"></a>        <span class="co"># Compute loss</span></span>
<span id="cb23-28"><a href="#cb23-28" aria-hidden="true" tabindex="-1"></a>        loss <span class="op">=</span> criterion(predictions, y_batch)</span>
<span id="cb23-29"><a href="#cb23-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-30"><a href="#cb23-30" aria-hidden="true" tabindex="-1"></a>        <span class="co"># Backpropagation</span></span>
<span id="cb23-31"><a href="#cb23-31" aria-hidden="true" tabindex="-1"></a>        loss.backward()</span>
<span id="cb23-32"><a href="#cb23-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-33"><a href="#cb23-33" aria-hidden="true" tabindex="-1"></a>        <span class="co"># Update model parameters</span></span>
<span id="cb23-34"><a href="#cb23-34" aria-hidden="true" tabindex="-1"></a>        optimizer.step()</span>
<span id="cb23-35"><a href="#cb23-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-36"><a href="#cb23-36" aria-hidden="true" tabindex="-1"></a>        running_train_loss <span class="op">+=</span> loss.item() <span class="op">*</span> X_batch.size(<span class="dv">0</span>)</span>
<span id="cb23-37"><a href="#cb23-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-38"><a href="#cb23-38" aria-hidden="true" tabindex="-1"></a>    epoch_train_loss <span class="op">=</span> running_train_loss <span class="op">/</span> <span class="bu">len</span>(train_loader.dataset)</span>
<span id="cb23-39"><a href="#cb23-39" aria-hidden="true" tabindex="-1"></a>    train_losses.append(epoch_train_loss)</span>
<span id="cb23-40"><a href="#cb23-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-41"><a href="#cb23-41" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Evaluation phase</span></span>
<span id="cb23-42"><a href="#cb23-42" aria-hidden="true" tabindex="-1"></a>    model.<span class="bu">eval</span>()</span>
<span id="cb23-43"><a href="#cb23-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-44"><a href="#cb23-44" aria-hidden="true" tabindex="-1"></a>    running_test_loss <span class="op">=</span> <span class="fl">0.0</span></span>
<span id="cb23-45"><a href="#cb23-45" aria-hidden="true" tabindex="-1"></a>    <span class="cf">with</span> torch.inference_mode():</span>
<span id="cb23-46"><a href="#cb23-46" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> X_batch, y_batch <span class="kw">in</span> test_loader:</span>
<span id="cb23-47"><a href="#cb23-47" aria-hidden="true" tabindex="-1"></a>            X_batch <span class="op">=</span> X_batch.to(device)</span>
<span id="cb23-48"><a href="#cb23-48" aria-hidden="true" tabindex="-1"></a>            y_batch <span class="op">=</span> y_batch.to(device)</span>
<span id="cb23-49"><a href="#cb23-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-50"><a href="#cb23-50" aria-hidden="true" tabindex="-1"></a>            predictions <span class="op">=</span> model(X_batch)</span>
<span id="cb23-51"><a href="#cb23-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-52"><a href="#cb23-52" aria-hidden="true" tabindex="-1"></a>            loss <span class="op">=</span> criterion(predictions, y_batch)</span>
<span id="cb23-53"><a href="#cb23-53" aria-hidden="true" tabindex="-1"></a>            running_test_loss <span class="op">+=</span> loss.item() <span class="op">*</span> X_batch.size(<span class="dv">0</span>)</span>
<span id="cb23-54"><a href="#cb23-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-55"><a href="#cb23-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-56"><a href="#cb23-56" aria-hidden="true" tabindex="-1"></a>    epoch_test_loss <span class="op">=</span> running_test_loss <span class="op">/</span> <span class="bu">len</span>(test_loader.dataset)</span>
<span id="cb23-57"><a href="#cb23-57" aria-hidden="true" tabindex="-1"></a>    test_losses.append(epoch_test_loss)</span>
<span id="cb23-58"><a href="#cb23-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-59"><a href="#cb23-59" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Save best model</span></span>
<span id="cb23-60"><a href="#cb23-60" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> epoch_test_loss <span class="op">&lt;</span> best_test_loss:</span>
<span id="cb23-61"><a href="#cb23-61" aria-hidden="true" tabindex="-1"></a>        best_test_loss <span class="op">=</span> epoch_test_loss</span>
<span id="cb23-62"><a href="#cb23-62" aria-hidden="true" tabindex="-1"></a>        best_model_state <span class="op">=</span> model.state_dict()</span>
<span id="cb23-63"><a href="#cb23-63" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-64"><a href="#cb23-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-65"><a href="#cb23-65" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (epoch <span class="op">+</span> <span class="dv">1</span>) <span class="op">%</span> PRINT_FREQ <span class="op">==</span> <span class="dv">0</span> <span class="kw">or</span> epoch <span class="op">==</span> <span class="dv">0</span>:</span>
<span id="cb23-66"><a href="#cb23-66" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-67"><a href="#cb23-67" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>( <span class="ss">f"Epoch [</span><span class="sc">{</span>epoch<span class="op">+</span><span class="dv">1</span><span class="sc">:3d}</span><span class="ss">/</span><span class="sc">{</span>EPOCHS<span class="sc">}</span><span class="ss">] "</span></span>
<span id="cb23-68"><a href="#cb23-68" aria-hidden="true" tabindex="-1"></a>               <span class="ss">f"| Train Loss (MSE): </span><span class="sc">{</span>epoch_train_loss<span class="sc">:.6f}</span><span class="ss"> "</span></span>
<span id="cb23-69"><a href="#cb23-69" aria-hidden="true" tabindex="-1"></a>               <span class="ss">f"| Test Loss (MSE): </span><span class="sc">{</span>epoch_test_loss<span class="sc">:.6f}</span><span class="ss">"</span></span>
<span id="cb23-70"><a href="#cb23-70" aria-hidden="true" tabindex="-1"></a>        )</span>
<span id="cb23-71"><a href="#cb23-71" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-72"><a href="#cb23-72" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">--- Training completed successfully! ---"</span>)</span>
<span id="cb23-73"><a href="#cb23-73" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-74"><a href="#cb23-74" aria-hidden="true" tabindex="-1"></a><span class="co"># Restore the best performing model</span></span>
<span id="cb23-75"><a href="#cb23-75" aria-hidden="true" tabindex="-1"></a>model.load_state_dict(best_model_state)</span>
<span id="cb23-76"><a href="#cb23-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-77"><a href="#cb23-77" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Best test MSE: </span><span class="sc">{</span>best_test_loss<span class="sc">:.6f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Configuring the training loop...
Epoch [  1/200] | Train Loss (MSE): 0.021064 | Test Loss (MSE): 0.017383
Epoch [ 10/200] | Train Loss (MSE): 0.002691 | Test Loss (MSE): 0.004228
Epoch [ 20/200] | Train Loss (MSE): 0.000863 | Test Loss (MSE): 0.001833
Epoch [ 30/200] | Train Loss (MSE): 0.000664 | Test Loss (MSE): 0.001922
Epoch [ 40/200] | Train Loss (MSE): 0.000595 | Test Loss (MSE): 0.001469
Epoch [ 50/200] | Train Loss (MSE): 0.000585 | Test Loss (MSE): 0.001208
Epoch [ 60/200] | Train Loss (MSE): 0.000544 | Test Loss (MSE): 0.001275
Epoch [ 70/200] | Train Loss (MSE): 0.000524 | Test Loss (MSE): 0.001497
Epoch [ 80/200] | Train Loss (MSE): 0.000493 | Test Loss (MSE): 0.001309
Epoch [ 90/200] | Train Loss (MSE): 0.000493 | Test Loss (MSE): 0.001442
Epoch [100/200] | Train Loss (MSE): 0.000474 | Test Loss (MSE): 0.001406
Epoch [110/200] | Train Loss (MSE): 0.000472 | Test Loss (MSE): 0.001250
Epoch [120/200] | Train Loss (MSE): 0.000449 | Test Loss (MSE): 0.001522
Epoch [130/200] | Train Loss (MSE): 0.000456 | Test Loss (MSE): 0.001183
Epoch [140/200] | Train Loss (MSE): 0.000432 | Test Loss (MSE): 0.001347
Epoch [150/200] | Train Loss (MSE): 0.000436 | Test Loss (MSE): 0.001405
Epoch [160/200] | Train Loss (MSE): 0.000414 | Test Loss (MSE): 0.001174
Epoch [170/200] | Train Loss (MSE): 0.000399 | Test Loss (MSE): 0.001183
Epoch [180/200] | Train Loss (MSE): 0.000403 | Test Loss (MSE): 0.001066
Epoch [190/200] | Train Loss (MSE): 0.000402 | Test Loss (MSE): 0.001330
Epoch [200/200] | Train Loss (MSE): 0.000392 | Test Loss (MSE): 0.001260

--- Training completed successfully! ---
Best test MSE: 0.001066</code></pre>
</div>
</div>
<div id="1c465af6" class="cell" data-execution_count="12">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.dates <span class="im">as</span> mdates</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"1. Generating predictions on the test set..."</span>)</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>model.<span class="bu">eval</span>()</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>predictions_list <span class="op">=</span> []</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>actuals_list <span class="op">=</span> []</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a><span class="cf">with</span> torch.inference_mode():</span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> X_batch, y_batch <span class="kw">in</span> test_loader:</span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a>        X_batch <span class="op">=</span> X_batch.to(device)</span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a>        preds <span class="op">=</span> model(X_batch)</span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a>        <span class="co"># Retrieving predictions and actual values on the CPU</span></span>
<span id="cb25-15"><a href="#cb25-15" aria-hidden="true" tabindex="-1"></a>        predictions_list.extend(preds.cpu().numpy())</span>
<span id="cb25-16"><a href="#cb25-16" aria-hidden="true" tabindex="-1"></a>        actuals_list.extend(y_batch.numpy())</span>
<span id="cb25-17"><a href="#cb25-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-18"><a href="#cb25-18" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. Inverting the normalization to return to kWh</span></span>
<span id="cb25-19"><a href="#cb25-19" aria-hidden="true" tabindex="-1"></a>predictions_rescaled <span class="op">=</span> scaler_y.inverse_transform(np.array(predictions_list))</span>
<span id="cb25-20"><a href="#cb25-20" aria-hidden="true" tabindex="-1"></a>actuals_rescaled <span class="op">=</span> scaler_y.inverse_transform(np.array(actuals_list))</span>
<span id="cb25-21"><a href="#cb25-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-22"><a href="#cb25-22" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"2. Plotting the Actual vs Predicted comparison with Dates..."</span>)</span>
<span id="cb25-23"><a href="#cb25-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-24"><a href="#cb25-24" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract the corresponding timestamps for the first 500 predictions</span></span>
<span id="cb25-25"><a href="#cb25-25" aria-hidden="true" tabindex="-1"></a><span class="co"># (Skipping the first SEQUENCE_LENGTH hours used for the first window)</span></span>
<span id="cb25-26"><a href="#cb25-26" aria-hidden="true" tabindex="-1"></a>SEQUENCE_LENGTH <span class="op">=</span> <span class="dv">24</span> </span>
<span id="cb25-27"><a href="#cb25-27" aria-hidden="true" tabindex="-1"></a>test_dates <span class="op">=</span> df_test.index[SEQUENCE_LENGTH : SEQUENCE_LENGTH <span class="op">+</span> <span class="dv">500</span>]</span>
<span id="cb25-28"><a href="#cb25-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-29"><a href="#cb25-29" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">14</span>, <span class="dv">6</span>))</span>
<span id="cb25-30"><a href="#cb25-30" aria-hidden="true" tabindex="-1"></a>plt.plot(test_dates, actuals_rescaled[:<span class="dv">500</span>], label<span class="op">=</span><span class="st">"Actual Consumption (kWh)"</span>, color<span class="op">=</span><span class="st">'black'</span>, alpha<span class="op">=</span><span class="fl">0.7</span>, linewidth<span class="op">=</span><span class="fl">1.5</span>)</span>
<span id="cb25-31"><a href="#cb25-31" aria-hidden="true" tabindex="-1"></a>plt.plot(test_dates, predictions_rescaled[:<span class="dv">500</span>], label<span class="op">=</span><span class="st">"LSTM Prediction (kWh)"</span>, color<span class="op">=</span><span class="st">'red'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>, linewidth<span class="op">=</span><span class="fl">1.5</span>)</span>
<span id="cb25-32"><a href="#cb25-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-33"><a href="#cb25-33" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Graham Building Digital Twin: Comparison over the first 500 test hours"</span>)</span>
<span id="cb25-34"><a href="#cb25-34" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Date"</span>)</span>
<span id="cb25-35"><a href="#cb25-35" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Consumption (kWh)"</span>)</span>
<span id="cb25-36"><a href="#cb25-36" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb25-37"><a href="#cb25-37" aria-hidden="true" tabindex="-1"></a>plt.grid(<span class="va">True</span>, alpha<span class="op">=</span><span class="fl">0.3</span>)</span>
<span id="cb25-38"><a href="#cb25-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-39"><a href="#cb25-39" aria-hidden="true" tabindex="-1"></a><span class="co"># Automatically format the x-axis dates to look clean and prevent overlapping</span></span>
<span id="cb25-40"><a href="#cb25-40" aria-hidden="true" tabindex="-1"></a>plt.gcf().autofmt_xdate()</span>
<span id="cb25-41"><a href="#cb25-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-42"><a href="#cb25-42" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb25-43"><a href="#cb25-43" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>1. Generating predictions on the test set...
2. Plotting the Actual vs Predicted comparison with Dates...</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="optitherm_files/figure-html/cell-13-output-2.png" width="1334" height="568" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<div id="faafd26b" class="cell" data-execution_count="13">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">5</span>))</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>plt.plot(train_losses, label<span class="op">=</span><span class="st">"Train Loss"</span>, color<span class="op">=</span><span class="st">'blue'</span>)</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>plt.plot(test_losses, label<span class="op">=</span><span class="st">"Test Loss"</span>, color<span class="op">=</span><span class="st">'orange'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>)</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Digital Twin Training Convergence"</span>)</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Epochs"</span>)</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"MSE Loss (Normalized)"</span>)</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>plt.grid(<span class="va">True</span>, alpha<span class="op">=</span><span class="fl">0.3</span>)</span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="optitherm_files/figure-html/cell-14-output-1.png" width="952" height="470" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<div id="ba47215a" class="cell" data-execution_count="14">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">6</span>, <span class="dv">6</span>))</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>plt.scatter(actuals_rescaled, predictions_rescaled, alpha<span class="op">=</span><span class="fl">0.3</span>, color<span class="op">=</span><span class="st">'purple'</span>, s<span class="op">=</span><span class="dv">10</span>, label<span class="op">=</span><span class="st">"Predictions"</span>)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Ideal line y = x</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>min_val <span class="op">=</span> <span class="bu">min</span>(actuals_rescaled.<span class="bu">min</span>(), predictions_rescaled.<span class="bu">min</span>())</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>max_val <span class="op">=</span> <span class="bu">max</span>(actuals_rescaled.<span class="bu">max</span>(), predictions_rescaled.<span class="bu">max</span>())</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>plt.plot([min_val, max_val], [min_val, max_val], color<span class="op">=</span><span class="st">'black'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>, linewidth<span class="op">=</span><span class="dv">2</span>, label<span class="op">=</span><span class="st">"Perfect Model"</span>)</span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Parity Plot: Actual vs Predicted"</span>)</span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Actual Consumption (kWh)"</span>)</span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Predicted Consumption (kWh)"</span>)</span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a>plt.grid(<span class="va">True</span>, alpha<span class="op">=</span><span class="fl">0.3</span>)</span>
<span id="cb28-14"><a href="#cb28-14" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb28-15"><a href="#cb28-15" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="optitherm_files/figure-html/cell-15-output-1.png" width="568" height="566" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<section id="conclusion-and-engineering-insights" class="level3">
<h3 class="anchored" data-anchor-id="conclusion-and-engineering-insights">5. Conclusion and Engineering Insights</h3>
<p>The development of the data-driven digital twin for the <em>Panther_office_Graham</em> building yielded highly promising results, demonstrating the viability of using deep learning for building energy modeling.</p>
<p>Based on the model’s outputs, we can draw the following key conclusions:</p>
<ul>
<li><strong>Accurate Capture of Thermal Dynamics:</strong> The time-series comparison shows that the LSTM network successfully learned the building’s operational schedule and thermal inertia. It accurately anticipates the sharp morning ramp-ups in energy consumption as well as the extended drops during nights and weekends.</li>
<li><strong>Robust Generalization (No Overfitting):</strong> The training convergence plot demonstrates that both the training and test losses stabilized quickly (within the first 25 epochs). The test loss remained consistently low without diverging, confirming that the chronological split and 24-hour sequence structure prevented data leakage and overfitting.</li>
<li><strong>High Reliability Across Load Profiles:</strong> The parity plot reveals a tight clustering of predictions along the ideal model line. The digital twin exhibits minimal bias across the entire consumption spectrum, performing just as reliably during peak load hours (~120 kWh) as it does during baseline operations (~30 kWh).</li>
</ul>
<p><strong>Next Steps:</strong> With a highly accurate and responsive digital twin established, the next logical phase in this project is the implementation of a <strong>Model Predictive Control (MPC)</strong> optimizer. By pairing this LSTM forward-prediction model with an optimization algorithm (such as Sequential Quadratic Programming or a Genetic Algorithm), we can actively compute optimal HVAC setpoints that minimize future energy costs while strictly enforcing occupant comfort constraints.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/itchinda\.github\.io\/portfolio");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>